### PR TITLE
feat: Add custom parameter support to hooks for multi tenant use cases

### PR DESCRIPTION
**Pull request by ghost**
This PR is related to #351

### CODE REVIEW

**Comment by mostafa** [comment]
@j0x539 Please sign the CLA.

**Review by mostafa — COMMENTED** [review]
Except a nit, overall LGTM!

**Comment by mostafa** [comment]
@j0x539 Can you please fix the failing CI steps. I think linter is complaining.

**Comment by j0x539** [comment]
> @j0x539 Can you please fix the failing CI steps. I think linter is complaining.

Sure thing, the codebase seems to put `# type: ignore` to suppress the linter warning for `run_hook` calls, is that a satisfying solution?

**Comment by j0x539** [comment]
I've been looking at the `signin` handler without realizing I essentially implemented what `sp_initiated_login` does. Though, we should still be helpful to pass a parameter such as the existing `user_id`  into `get_custom_acs_url` don't you think?

**Comment by j0x539** [comment]
You're right, I figured that out now, thank you. if there's any part of the changes which you might still deem useful I'll be happy to make changes otherwise we can close the PR and related issue - not sure why the test deployment fails now. Also could you redact my name in the two instances CLAassistant mentioned it? :pray:

**Comment by mostafa** [comment]
@j0x539 I'll have another look tomorrow and then we can decide what to do with this.

**Comment by j0x539** [comment]
This and #351 can probably be closed now. Could you look into my request in the previous comment? Thank you :pray:

**Pull request closed without merging**
